checks:
    php: true
filter:
    excluded_paths:
        - 'tests/*'
build:
    tests:
        override:
            -
                command: 'phpunit --bootstrap vendor/autoload.php --coverage-clover=some-file tests'
                coverage:
                    file: 'coverage-file'
                    format: 'clover'
