---
data_dir : #Dateipfad zum ablegen der ILIAS Daten außerhalb des Webserverser /Users/user/data
default_name : #Name des Clients
default_password_encoder : #encoder für Passwörter der Benutzer (md5 || bcrypt)
host: #host von ILIAS
database: #Datenbankname
user: #Datenbankbenutzer
password: #Benutzerpasswort
type: #Datenbankengine (innodb)
encoding: # encoding der Datenbank (utf8_general_ci)
default_lang: #Sprache die im Standard verwendet werden soll (de)
to_install_langs: #array von sprachen die installiert werden sollen 
    #- en 
    #- de
http_path: #http pafad für die ILIAS installation (host/client_id)
absolute_path: #pfad wo die ILIAS Dateien liegen (/Library/WebServer/Documents/iliastest)
timezone: #Zeitzone (Europe/Berlin)
passwd: #Admin Passwort für das Setup
convert: #Dateipfad zum IMG Converter
zip: #Dateipfad zu ZIP
unzip: #Dateipfad zu UNZIP
java: #Dateipfad zu Java
path: #Pfad wo ILIAS die Logdatei ablegen soll
file_name: #Name der Logdatei
git_url: #URL des Git Repo
git_branch_name: #BranchName